/* Generated by Opal 0.7.2 */
(function(Opal) {
  Opal.dynamic_require_severity = "error";
  var $a, $b, TMP_1, self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice, $gvars = Opal.gvars;
  if ($gvars.document == null) $gvars.document = nil;

  Opal.add_stubs(['$ready', '$puts']);
  self.$require("browser");
  return ($a = ($b = $gvars.document).$ready, $a.$$p = (TMP_1 = function(){var self = TMP_1.$$s || this;

  return self.$puts("yo dawg, I'm all loaded up in here")}, TMP_1.$$s = self, TMP_1), $a).call($b);
})(Opal);
